import '../../styles/style.css';
import '../../styles/chat.css';
import '../../partials/avatar/avatar-chat.css';
import '../../partials/chat-preview/chat-preview.css';
import '../../partials/input/input-text.css';
import '../../partials/menu/menu-attach.css';
import '../../partials/menu/menu-burger.css';
import '../../partials/message/my-message.css';
import '../../partials/message/message.css';
